### ISSUE TITLE
should we align statements?

### ISSUE THREAD

**Issue by kaievns** [Prismatik/eslint-config-prismatik#1]
this is a thing that popped out in `redbeard`. i kind of guilty for liking pretty code, so I normally align assignment statements and object key/values, like so:

``` js
const bla       = require("bla");
const bla1      = require('bla-one');
const something = require('bla');

const object = {
  bla:       'one',
  bla1:      'another',
  something: 'else'
};
```

i just find it is easier to work with code this way, that's pretty much my reasoning.

and so I was wondering if anyone else is interested in doing the same thing. you obviously don't have to
do that manually, there are plugins for that.

the negative side of it, that sometimes when you add something with a longer name than everything else, you'd have to realign everything and it will pop up in git diff. but then again, there is always a cost to being pretty, right?

**Comment by lyntco** [comment]
I actually dislike this way because I am lazy lol. Having to spend extra time re-aligning letters doesn't feel right to me.

**Comment by nwinch** [comment]
I actually think the opposite - it looks prettier non-aligned ;)

**Comment by Nicktho** [comment]
I'm with lyn and nath. Realigning is too much effort (lol) and I find it quite hard to read. I figure reading it will become easier once I get used it to, but meh.

**Comment by kaievns** [comment]
yeah, all good then :)
