### ISSUE TITLE
camelcase rule vs rethinkdb vars

### ISSUE THREAD

**Issue by nwinch** [Prismatik/eslint-config-prismatik#22]
Just got pinged on this one so I thought I'd open a discussion.  `rethinkdb` names return vars as `new_val` and `old_val`, but this gets caught by the linter rule `camelcase`.

I think we're all happy with the linter rule (I prefer camelCase), but as we are going to be using `rethinkdb` more and more, what to do?

Possible solutions:
1. Rename eg. `new_val as newVal` when using it.  This feels errk, as you'll need to do that umpteen times.
2. We could add a middleware adaptor (just for redbeard I guess) for any `rethinkdb` libs we make which renames the vars on the way out?  Seems heavy handed just to please the linter though.
3. Turn camelcase rule off?  As I said, I think we all prefer camelCase, but we're bound to find many external libs/plugins that don't play nice with our linter.  So we either need to loosen our grip on some rules, or have to work to adapt those libs/plugins.

Thoughts?

**Comment by davidbanham** [comment]
I agree. Doing all that work to mutate the parameters just to pass a lint rule seems like misallocated effort.

I think ideally we'd add some kind of exception to the rule. Like "if it's either new_val or old_val then we're cool"

Failing that, just switch it off. The primary purpose of the linter is to catch errors like variables being declared twice, etc. Casing is both obvious when you're doing it wrong and low impact. The safest kind of rule to switch off, IMO.

**Comment by kaievns** [comment]
you could place a local eslint override in a comment for that line of code. there obviously will be exceptions like that here and there. bending to the linter doesn't make sense in this case

**Comment by kaievns** [comment]
as there was no further discussion, i'm closing this in favor of local eslint overrides on per project/case basis
