### ISSUE TITLE
Bump "eslint" to new major v3

### ISSUE THREAD

**Issue by nwinch** [Prismatik/eslint-config-prismatik#23]
The dependency `eslint-config-airbnb` et al packages use `eslint` as a peer dependency so this will complain for newer projects that install `eslint@3`.

**Comment by kaievns** [comment]
good thinking, thanks!

**Comment by kaievns** [comment]
resolved in https://github.com/Prismatik/eslint-config-prismatik/commit/bceb931328e543cdda84417d3abb1009dbf3e0eb
