### ISSUE TITLE
curly spaces

### ISSUE THREAD

**Issue by kaievns** [Prismatik/eslint-config-prismatik#24]
so, here is a thing that bugs me with out current setup a bit: the airbnb config requires spaces after `{` and before `}`, which is fine on its own. it event looks in a way pretty. but, then the same config requires no spaces after `{` and before `}` in JSX component props. also it requires no spaces before and after `[]`, which doesn't make much sense to me.

so, my sense is that we have two options here:

1) remove spaces after `{` and before `}`
2) make it require spaces after `{` and before `}` in JSX props and also after `[` and before `]`, to make it consistent

so, could you please put comments who's in favor of `1`, and who likes `2` more. also if you feel like the current system makes sense, please speak up. thanks!

**Comment by nwinch** [comment]
I'm used to current setup, so would be happy to leave as is.

But if I had to vote from the above, I'd choose more space than less, so 2.

**Comment by lyntco** [comment]
I prefer spaces for `{ key: 'value' }` and `{ props.name }` but i dont think `[1, 2, 3]` needs it

**Comment by s-taylor** [comment]
I'm kinda happy to leave it as is as well. Though, if I had to choose from the above I'd vote for adding spaces to arrays.

**Comment by Nicktho** [comment]
I totally agree that the requirement for no-spaces in props is annoying but I see its value and why airbnb implemented it, that being that props aren't objects and the space after `{` and before `}` are reserved for objects so that as a developer you can quickly identify what's what.

``` js
const value = 18

<Something anObject={{ value }} />

<SomethingElse anInteger={value} />
```

``` js
anObject === { value: 18 }
anInteger === 18
```

EDIT: realised that `anObject === { value: 18 }` is technically false cause object literals but lol you know what i mean

**Comment by Nicktho** [comment]
it would of been better if facebook chose something other than `{` and `}` to wrap their values in JSX

**Comment by kaievns** [comment]
a great point Nick, thanks! i don't want to make the spaces optional, as it will breed syntax inconsistency. so, as it apparently doesn't rub anyone else the wrong way that much, i'll just leave this as it is by default
